### ISSUE TITLE
OpenAI native chat history breaks export

### ISSUE THREAD

**Issue by matthewdeanmartin** [esteinmann/chatgpt-convdown#8] opened 2022-12-21 19:42 UTC
On firefox, on windows the green arrow disappears as soon as you click an historical chat.

The latest UI update is breaking most exporters on most browsers on most OSs, so that is probably the real problem, not the particular browser or OS I'm using.

**Comment by esteinmann** [comment] 2022-12-21 21:25
Hello, thank you for reporting this issue. 

I agree that this is universal and has nothing to do with your OS. The behavior of the site has just changed. 

The issue is/was that when navigating to individual chats (path chat/{guid}) the browser does not do a full reload of the page, so the content script is not triggered anymore. Therefore I changed the script to monitor navigation changes on chat.openai.com and fire the content script after a small delay (1 sec). This should bring the button back.

Can you try updating the extension to version 4.0?

**Comment by esteinmann** [comment] 2022-12-23 19:41
I regard this as fixed in version 4.0 now

**Closed by esteinmann** 2022-12-23 19:41 UTC
